# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a510c5c24e3cd5abbf1c3e5012b404893efb5a0c9c83a57f22ada8fe2c6645fca186f6f33260e0b897965847d18ef8b9a89e49183fbcffe6bbcb1426e1877a91

test:
  secret_key_base: 238371cabefa1ab18fec4ad043b3ba3632b2aec980cac1efb70154137bdceb483d036f42434a7bb1623787e01eb1b05882d129fd5712804bf288e447fd24d356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
